FROM node:24-bookworm-slim

WORKDIR /app

RUN corepack enable

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
COPY apps ./apps
COPY packages ./packages

RUN pnpm install --frozen-lockfile
RUN pnpm --filter @clinic/queues build \
  && pnpm --filter @clinic/worker build

ENV NODE_ENV=production

CMD ["pnpm", "--filter", "@clinic/worker", "start"]
