FROM node:24-bookworm-slim

WORKDIR /app

RUN corepack enable

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
COPY apps ./apps
COPY packages ./packages

RUN pnpm install --frozen-lockfile
RUN pnpm --filter @clinic/database build \
  && pnpm --filter @clinic/queues build \
  && pnpm --filter @clinic/api build

ENV NODE_ENV=production
ENV API_PORT=3000

EXPOSE 3000

CMD ["sh", "apps/api/start.sh"]
